feat(dockerize-env) init docker
shadownetX/terraqueus-back pull request #1
Opened 2018-02-15 18:59 UTC by shadownetX

2018-02-18 20:10 UTC, nicolas-grevin requested changes

2018-02-18 20:10 UTC, nicolas-grevin commented on README.md
> +| **For short** | **Makefile command**        | **Docker command**                  | **Purpose**                          |
En faite `Docker command` c'est pas des commandes docker c'esr inssue d'un script

2018-02-18 20:10 UTC, nicolas-grevin commented on Makefile
> +	@bin/docker build
Tu aurais du faire un choix entre srcipt et Make

2018-02-18 20:10 UTC, nicolas-grevin commented on assets/css/app.scss
> +$background: lightgreen;
rgba ou exa

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/docker-compose.yml
> +            - ${LOGS_DIR}/symfony:${SYMFONY_DOCKER_PATH}${SYMFONY_DOCKER_PATH_LOG}
Laisse les logs de symfony tranquilement ou ils sont !!!! 
Si tu as envie d'utiliser un elkb tu aura des problème

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/docker-compose.yml
> +            - ${LOGS_DIR}/nginx/:${NGINX_DOCKER_PATH_LOG}
idem laisse les logs tranquille

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/nginx/Dockerfile
> +MAINTAINER Thomas THIEBAUDET <thomas@thiebaudet.fr>
C'est une image open source ?

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/node/Dockerfile
> +MAINTAINER Thomas THIEBAUDET <thomas@thiebaudet.fr>
open source ?

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/php/Dockerfile
> +MAINTAINER Thomas THIEBAUDET <thomas@thiebaudet.fr>
open source ?

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/php/Dockerfile
> +# Install Composer and fix flex permissions to https---symfony.sh
C'est une installation de composer bien complexe
```Dockerfile
ENV COMPOSER_HOME /var/composer
ENV COMPOSER_ALLOW_SUPERUSER 1

RUN mkdir -p /var/composer \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer global require hirak/prestissimo -o --prefer-dist --no-progress --no-suggest \
    && composer clear-cache
```

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/php/Dockerfile
> +# Set timezone
Sur les image alpine tu peux faire ça
```Dockerfile
RUN apk add tzdata
ENV TZ Europe/Paris
```

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/php/Dockerfile
> +ADD php.ini /usr/local/etc/php
Link depuis le manifeste de docker compose, cette image peut être réutilisé

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/php/Dockerfile
> +WORKDIR /var/www/symfony-back
dans le manfifeste de docker-compose, on peut la retulisé

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/php/Dockerfile
> +FROM php:7.2-fpm-alpine
Ajout a la fini un clean `RUN rm -rf /var/cache/apk && mkdir -p /var/cache/apk` j'update mon article avant ça parrution 😉

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/node/Dockerfile
> +RUN npm install
NON

2018-02-18 20:10 UTC, nicolas-grevin commented on docker/node/Dockerfile
> +CMD [ "npm", "start" ]
docker-compose est la pour ça

2018-02-19 15:41 UTC, shadownetX commented on Makefile
> +	@bin/docker build
c'est à dire ?

2018-02-19 15:41 UTC, shadownetX commented on assets/css/app.scss
> +$background: lightgreen;
LOL

2018-02-19 15:42 UTC, shadownetX commented on README.md
> +| **For short** | **Makefile command**        | **Docker command**                  | **Purpose**                          |
c'est noté !

2018-02-19 15:42 UTC, shadownetX commented on docker/docker-compose.yml
> +            - ${LOGS_DIR}/symfony:${SYMFONY_DOCKER_PATH}${SYMFONY_DOCKER_PATH_LOG}
c'est noté !

2018-02-19 15:42 UTC, shadownetX commented on docker/docker-compose.yml
> +            - ${LOGS_DIR}/nginx/:${NGINX_DOCKER_PATH_LOG}
c'est noté !

2018-02-19 15:42 UTC, shadownetX commented on docker/php/Dockerfile
> +ADD php.ini /usr/local/etc/php
c'est noté !

2018-02-19 15:42 UTC, shadownetX commented on docker/php/Dockerfile
> +WORKDIR /var/www/symfony-back
c'est noté !

2018-02-19 15:42 UTC, shadownetX commented on docker/php/Dockerfile
> +FROM php:7.2-fpm-alpine
c'est noté !

2018-02-19 15:43 UTC, shadownetX commented on docker/node/Dockerfile
> +RUN npm install
alors comment ?

2018-02-19 15:43 UTC, shadownetX commented on docker/node/Dockerfile
> +CMD [ "npm", "start" ]
c'est noté !

2018-02-19 15:44 UTC, shadownetX commented on docker/nginx/Dockerfile
> +MAINTAINER Thomas THIEBAUDET <thomas@thiebaudet.fr>
Tu veux dire que le caractère opensource de l'app ne rend pas obligatoire `MAINTAINER` ?

2018-02-19 15:46 UTC, shadownetX commented on docker/php/Dockerfile
> +# Install Composer and fix flex permissions to https---symfony.sh
Merci !

2018-02-19 15:46 UTC, shadownetX commented on docker/php/Dockerfile
> +# Set timezone
Merci, je vais tester !

2018-02-19 15:55 UTC, nicolas-grevin commented on docker/node/Dockerfile
> +RUN npm install
oui dans le docker-compose.yml tu peux faire :
```yaml
node:
     image: node:9-alpine / node:9
     ...
    command: sh -c "npm install  && npm start" / bash -c "npm install && npm start"
```

2018-02-19 16:04 UTC, nicolas-grevin requested changes

2018-02-19 16:04 UTC, nicolas-grevin commented on Makefile
> +	@bin/docker build
enfait la ton `bin/docker build` fait fait juste un `docker-compose build [OPTIONS]` mais tu peux le faire directement dans le makefile :
```makefile
build: 
     $(info --> Build application)
     @docker-compose build [OPTIONS]
```

2018-02-19 16:04 UTC, nicolas-grevin commented on docker/nginx/Dockerfile
> +MAINTAINER Thomas THIEBAUDET <thomas@thiebaudet.fr>
Non si tu reste en projet fermer tu ne met jamais ton nom mais si tu image est proposer et distribuer alors la tu met ton nom.
De plus la notation a changer `MAINTAINER` est deprecated => https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

2018-02-19 20:00 UTC, shadownetX commented on assets/css/app.scss
> +$background: lightgreen;
C'est modifié.

2018-02-19 20:04 UTC, shadownetX commented on docker/docker-compose.yml
> +            - ${LOGS_DIR}/symfony:${SYMFONY_DOCKER_PATH}${SYMFONY_DOCKER_PATH_LOG}
C'est modifié.

2018-02-19 20:04 UTC, shadownetX commented on docker/docker-compose.yml
> +            - ${LOGS_DIR}/nginx/:${NGINX_DOCKER_PATH_LOG}
C'est modifié.

2018-02-19 20:04 UTC, shadownetX commented on docker/nginx/Dockerfile
> +MAINTAINER Thomas THIEBAUDET <thomas@thiebaudet.fr>
C'est modifié.

2018-02-19 20:04 UTC, shadownetX commented on docker/node/Dockerfile
> +MAINTAINER Thomas THIEBAUDET <thomas@thiebaudet.fr>
C'est modifié.

2018-02-19 20:04 UTC, shadownetX commented on docker/php/Dockerfile
> +MAINTAINER Thomas THIEBAUDET <thomas@thiebaudet.fr>
C'est modifié.

2018-02-19 20:05 UTC, shadownetX commented on docker/php/Dockerfile
> +WORKDIR /var/www/symfony-back
C'est modifié.

2018-02-19 20:06 UTC, shadownetX commented on docker/php/Dockerfile
> +FROM php:7.2-fpm-alpine
C'est modifié.

2018-02-19 20:07 UTC, shadownetX commented on docker/node/Dockerfile
> +RUN npm install
C'est modifié.

2018-02-19 20:07 UTC, shadownetX commented on docker/node/Dockerfile
> +CMD [ "npm", "start" ]
C'est modifié.

2018-02-19 20:09 UTC, shadownetX commented on Makefile
> +	@bin/docker build
Pour l'instant je laisse comme cela, nous aurons l'occassion d'en reparler ;)

2018-02-19 20:10 UTC, shadownetX commented on docker/php/Dockerfile
> +# Install Composer and fix flex permissions to https---symfony.sh
C'est modifié.

2018-02-19 20:12 UTC, shadownetX commented on docker/php/Dockerfile
> +# Set timezone
C'est modifié.

2018-02-19 20:13 UTC, shadownetX commented on docker/php/Dockerfile
> +ADD php.ini /usr/local/etc/php
C'ets modifié.

2018-02-19 20:37 UTC, shadownetX commented on docker/php/Dockerfile
> +FROM php:7.2-fpm-alpine
Mais de manière plus propre je te conseille plutôt cette solution plus courte : `RUN rm -rf /var/cache/apk/*` comme ça pas besoin de recréer le répertoire ensuite. J'ai pas rencontré de problèmes avec cette solution !

2018-02-20 19:12 UTC, nicolas-grevin commented on docker/php/Dockerfile
> +FROM php:7.2-fpm-alpine
Après c'est une solution trouvé sur internet :smile:

Mais effectivement très bonne solution :wink:

2018-02-20 19:14 UTC, nicolas-grevin approved these changes

2018-02-20 19:16 UTC, nicolas-grevin commented
OK pour merge :smile: 

Tips : essaie d'avoir les plus petite PR possible :wink:

2018-02-20 22:12 UTC, shadownetX commented
Pas de soucis @nicolas-grevin :D Mes prochaines PR seront plus courtes et concises ;)

2018-02-28 09:27 UTC, shadownetX commented
Je suis prêt à MERGE :+1:

2018-02-28 10:23 UTC, merged